sudo: false
language: python

python:
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - "pip install -r requirements.txt"
 - pip install codecov

# - "pip install tox-travis"

script:
- py.test --cov postcard_creator

#script: tox

#install:


after_success:
  - codecov